# Generated by Django 3.1.6 on 2021-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20210215_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='cycle_with',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
